In [1]:
import pandas as pd
import matplotlib.pyplot as plt

# create a function to check three key data quality issues: data types, duplicates, missing values
def check_data_quality(data):
    # check data types
    print(data.info())
    
    # Check for duplicate rows
    print(f"Duplicate rows in data:{data.duplicated().sum()}")
    
    # Check for missing values
    print(f"Missing values in data:\n{data.isnull().sum()}") 

# create a function to check for outliers by using boxplots for numerical columns
def check_outliers(data, column):
    plt.boxplot(data[column])
    plt.title(f'Boxplot of {column}')
    plt.ylabel(column)
    plt.show()

# create a function to show outliers in the  column
def show_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] < lower_bound) | (df[column] > upper_bound)].sort_values(by=column, ascending=False) 


# create a function to check data consistancy in catgorical column
def check_data_consistency(data, column):
    value_counts = data[column].value_counts()
    print(f"Value counts in {column}:\n{value_counts}")

In [2]:
marketing_spend = pd.read_csv('marketing_spend.csv')
display(marketing_spend.head())

# convert the 'date' column to datetime format
marketing_spend['month'] = pd.to_datetime(marketing_spend['month'], format='%Y-%m')

,month,platform,spend,impressions,clicks,conversions,revenue_attributed,cpc,cpa,roas
0,2024-01,Google Ads,2676.14,303594,13271,500,43063.16,0.20,5.35,16.09
1,2024-01,Facebook Ads,1971.43,338022,7163,333,15950.86,0.28,5.92,8.09
2,2024-01,Instagram Ads,2418.95,561361,18729,748,54454.46,0.13,3.23,22.51
3,2024-01,TikTok Ads,1141.70,554273,6967,346,22369.23,0.16,3.30,19.59
4,2024-01,Email Marketing,868.82,29509,1215,58,4223.97,0.72,14.98,4.86

In [6]:
order_data = pd.read_csv('orders.csv')


# convert the 'order_date' column to datetime format
order_data['order_date'] = pd.to_datetime(order_data['order_date'], format='%Y-%m-%d')

# recalculate the 'total_costs' to ensure accuracy
order_data['total_costs'] = order_data['product_cost'] + order_data['shipping_cost'] + order_data['transaction_fee'] + order_data['platform_fee']

# recalculate the 'profit' to ensure accuracy
order_data['profit'] = order_data['gross_revenue'] - order_data['total_costs']

In [7]:
product_data = pd.read_csv('products.csv')
display(product_data.head())

,product_id,product_name,category,sub_category,unit_cost,selling_price,shipping_cost_per_unit,weight_lbs,supplier
0,SKU-0001,Headphones - Variant 1,Electronics,Headphones,29.44,56.08,13.42,12.4,Supplier A
1,SKU-0002,Headphones - Variant 2,Electronics,Headphones,26.92,91.57,15.50,15.0,Supplier B
2,SKU-0003,Headphones - Variant 3,Electronics,Headphones,15.91,43.34,9.58,7.6,Supplier C
3,SKU-0004,Headphones - Variant 4,Electronics,Headphones,7.13,24.31,5.74,2.8,Supplier B
4,SKU-0005,Headphones - Variant 5,Electronics,Headphones,43.05,135.82,5.82,2.9,Supplier C

In [9]:
from sqlalchemy import create_engine
from dotenv import load_dotenv
import pandas as pd
import os

load_dotenv()


db_password = os.getenv("DB_PASSWORD")

connection_string = (
    f"mysql+pymysql://root:{db_password}@localhost/e_commerce_profitability_analysis"
)

engine = create_engine(connection_string)

tables = {
    "marketing_spend": marketing_spend,
    "orders": order_data,
    "products": product_data
}

for table_name, df in tables.items():
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",   # use "append" if table already exists
        index=False
    )

print(" All tables imported successfully!")

 All tables imported successfully!